User.create(:first_name => 'Nealon', :last_name => 'Young', :email => 'nealony@uci.edu', :password => 'asdf', :password_confirmation => 'asdf')
User.create(:first_name => 'Michael', :last_name => 'Bulotano', :email => 'mbulotan@uci.edu', :password => 'asdf', :password_confirmation => 'asdf')
User.create(:first_name => 'Lance', :last_name => 'Mar', :email => 'lcmar@uci.edu', :password => 'asdf', :password_confirmation => 'asdf')

Course.create(:department => 'ANTHRO', :number => '2A', :created_by => 2)
Course.create(:department => 'ANTHRO', :number => '2B', :created_by => 2)
Course.create(:department => 'ANTHRO', :number => '2C', :created_by => 2)
Course.create(:department => 'ANTHRO', :number => '10C', :created_by => 2)
Course.create(:department => 'ANTHRO', :number => '41A', :created_by => 2)
Course.create(:department => 'ART STU', :number => '1C', :created_by => 2)
Course.create(:department => 'ART STU', :number => '20A', :created_by => 2)
Course.create(:department => 'ART STU', :number => '20B', :created_by => 2)
Course.create(:department => 'ART STU', :number => '30A', :created_by => 2)
Course.create(:department => 'ART STU', :number => '40', :created_by => 2)
Course.create(:department => 'BIO SCI', :number => '44', :created_by => 2)
Course.create(:department => 'BIO SCI', :number => '47', :created_by => 2)
Course.create(:department => 'BIO SCI', :number => '93', :created_by => 2)
Course.create(:department => 'BIO SCI', :number => '99', :created_by => 2)
Course.create(:department => 'COMPSCI', :number => '112', :created_by => 3)
Course.create(:department => 'COMPSCI', :number => '116', :created_by => 3)
Course.create(:department => 'COMPSCI', :number => '121', :created_by => 3)
Course.create(:department => 'COMPSCI', :number => '122A', :created_by => 3)
Course.create(:department => 'COMPSCI', :number => '122B', :created_by => 1)
Course.create(:department => 'COMPSCI', :number => '141', :created_by => 3)
Course.create(:department => 'ECON', :number => '15A', :created_by => 3)
Course.create(:department => 'ECON', :number => '15B', :created_by => 3)
Course.create(:department => 'ECON', :number => '20A', :created_by => 3)
Course.create(:department => 'ECON', :number => '20B', :created_by => 3)
Course.create(:department => 'ECON', :number => '25', :created_by => 3)
Course.create(:department => 'ECON', :number => '100B', :created_by => 3)
Course.create(:department => 'ECON', :number => '100C', :created_by => 3)
Course.create(:department => 'ECON', :number => '116A', :created_by => 3)
Course.create(:department => 'EECS', :number => '20', :created_by => 3)
Course.create(:department => 'EECS', :number => '31', :created_by => 3)
Course.create(:department => 'EECS', :number => '40', :created_by => 3)
Course.create(:department => 'EECS', :number => '70A', :created_by => 3)
Course.create(:department => 'ENGRMAE', :number => '10', :created_by => 3)
Course.create(:department => 'ENGRMAE', :number => '52', :created_by => 3)
Course.create(:department => 'ENGRMAE', :number => '80', :created_by => 3)
Course.create(:department => 'FLM&MDA', :number => '85C', :created_by => 3)
Course.create(:department => 'FLM&MDA', :number => '101B', :created_by => 3)
Course.create(:department => 'I&C SCI', :number => '6B', :created_by => 1)
Course.create(:department => 'I&C SCI', :number => '31', :created_by => 3)
Course.create(:department => 'I&C SCI', :number => '32', :created_by => 3)
Course.create(:department => 'I&C SCI', :number => '33', :created_by => 3)
Course.create(:department => 'I&C SCI', :number => '62', :created_by => 3)
Course.create(:department => 'I&C SCI', :number => '77B', :created_by => 3)
Course.create(:department => 'I&C SCI', :number => '77D', :created_by => 3)
Course.create(:department => 'I&C SCI', :number => '139W', :created_by => 1)
Course.create(:department => 'IN4MATX', :number => '43', :created_by => 3)
Course.create(:department => 'IN4MATX', :number => '101', :created_by => 3)
Course.create(:department => 'IN4MATX', :number => '115', :created_by => 3)
Course.create(:department => 'IN4MATX', :number => '123', :created_by => 3)
Course.create(:department => 'IN4MATX', :number => '124', :created_by => 3)
Course.create(:department => 'MATH', :number => '2A', :created_by => 3)
Course.create(:department => 'MATH', :number => '2B', :created_by => 3)
Course.create(:department => 'MATH', :number => '2D', :created_by => 3)
Course.create(:department => 'MATH', :number => '6G', :created_by => 3)
Course.create(:department => 'MATH', :number => '8', :created_by => 3)
Course.create(:department => 'MATH', :number => '13', :created_by => 3)
Course.create(:department => 'MATH', :number => '77B', :created_by => 3)
Course.create(:department => 'PHYSICS', :number => '3B', :created_by => 3)
Course.create(:department => 'PHYSICS', :number => '3C', :created_by => 3)
Course.create(:department => 'PHYSICS', :number => '7C', :created_by => 3)
Course.create(:department => 'PHYSICS', :number => '7D', :created_by => 3)
Course.create(:department => 'PHYSICS', :number => '51B', :created_by => 3)
Course.create(:department => 'PHYSICS', :number => '52C', :created_by => 3)
Course.create(:department => 'PSYCH', :number => '7A', :created_by => 3)
Course.create(:department => 'PSYCH', :number => '9A', :created_by => 3)
Course.create(:department => 'PSYCH', :number => '9B', :created_by => 3)
Course.create(:department => 'PSYCH', :number => '9C', :created_by => 3)
Course.create(:department => 'SOC SCI', :number => '1A', :created_by => 3)
Course.create(:department => 'SOC SCI', :number => '3A', :created_by => 3)
Course.create(:department => 'SOC SCI', :number => '10A', :created_by => 3)
Course.create(:department => 'SOC SCI', :number => '10B', :created_by => 3)
Course.create(:department => 'WRITING', :number => '30', :created_by => 3)
Course.create(:department => 'WRITING', :number => '39A', :created_by => 3)
Course.create(:department => 'WRITING', :number => '39B', :created_by => 3)
Course.create(:department => 'WRITING', :number => '39C', :created_by => 3)
Course.create(:department => 'WRITING', :number => '39A', :created_by => 3)
Course.create(:department => 'WRITING', :number => '91', :created_by => 3)

Assignment.create(:title => 'Project 1', :notes => 'JDBC Connections', :due => '2013-1-21', :course_id => 5)
Assignment.create(:title => 'Project 2', :notes => 'Java EE Web Applications', :due => '2013-2-8', :course_id => 5)
Assignment.create(:title => 'Project 3', :notes => 'MySQL User Management', :due => '2013-2-20', :course_id => 5)
Assignment.create(:title => 'Project 4', :notes => 'XML and AJAX', :due => '2013-3-4', :course_id => 5)
Assignment.create(:title => 'Project 5', :notes => 'Android Applications', :due => '2013-3-18', :course_id => 5)

Assignment.create(:title => 'Homework 1', :notes => 'SIMPLESEM Parsing', :due => '2013-2-1', :course_id => 6)
Assignment.create(:title => 'Homework 2', :notes => 'SIMPLESEM Semantics', :due => '2013-2-14', :course_id => 6)
Assignment.create(:title => 'Homework 3', :notes => 'C1-C4'' Conversions', :due => '2013-2-28', :course_id => 6)

Assignment.create(:title => 'Resume Draft', :notes => 'In-class peer review on Thursday', :due => '2013-1-17', :course_id => 14)
Assignment.create(:title => 'Resume Final', :notes => '',  :due => '2013-1-22', :course_id => 14)
Assignment.create(:title => 'Personal Statement Draft', :notes => 'Bring paper copy to class', :due => '2013-1-29', :course_id => 14)
Assignment.create(:title => 'Personal Statement Final', :notes => '',  :due => '2013-2-12', :course_id => 14)
Assignment.create(:title => 'Pitch Presentation', :notes => 'Submit slides to EEE Dropbox by 12:20AM day of presentation', :due => '2013-2-14', :course_id => 14)
Assignment.create(:title => 'Wikipedia Draft', :notes => '',  :due => '2013-2-12', :course_id => 14)
Assignment.create(:title => 'Wikipedia Final', :notes => 'Turn in permalink to copy of page',  :due => '2013-2-21', :course_id => 14)
